# Generated by Django 4.1.2 on 2022-10-12 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='apartment',
            field=models.CharField(blank=True, max_length=100, verbose_name='квартира'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='building',
            field=models.CharField(blank=True, max_length=100, verbose_name='корпус'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='city',
            field=models.CharField(blank=True, max_length=100, verbose_name='город'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='house',
            field=models.CharField(blank=True, max_length=100, verbose_name='дом'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone',
            field=models.CharField(blank=True, max_length=13),
        ),
        migrations.AddField(
            model_name='customuser',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20, verbose_name='почтовый индекс'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='street',
            field=models.CharField(blank=True, max_length=100, verbose_name='улица'),
        ),
    ]
