version: '3.7'
services:
    web:
        build: .
        command: gunicorn online_shop.wsgi -b 0.0.0.0:8000
        environment:
            - ENVIRONMENT=development
            - SECRET_KEY=$SECRET_KEY
            - DEBUG=1
            - DEFAULT_FROM_EMAIL=$DEFAULT_FROM_EMAIL
            - EMAIL_HOST_USER=$EMAIL_HOST_USER
            - EMAIL_HOST_PASSWORD=$EMAIL_HOST_PASSWORD
        ports:
            - 8000:8000
        depends_on:
            - db
    db:
        image: postgres:11
        environment:
          POSTGRES_DB: "$POSTGRES_DB"
          POSTGRES_PASSWORD: "$POSTGRES_PASSWORD"

