# Generated by Django 4.1.2 on 2022-10-26 12:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0004_alter_product_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Принято в обработку', 'Принято в обработку'), ('Упакован и отправлен', 'Упакован и отправлен'), ('Доставлен покупателю', 'Доставлен покупателю'), ('Отменен', 'Отменен')], default='Принято в обработку', max_length=50, verbose_name='Статус заказа')),
                ('payment', models.CharField(choices=[('Наличные', 'Наличные при получении'), ('Оплата картой', 'Оплата картой')], max_length=50, verbose_name='Способ оплаты')),
                ('delivery', models.CharField(choices=[('Самовывоз', 'Самовывоз'), ('Курьер', 'Курьер'), ('Почта', 'Почта')], max_length=50, verbose_name='Способ доставки')),
                ('phone', models.CharField(max_length=13, verbose_name='Телефон')),
                ('postal_code', models.CharField(blank=True, max_length=20, verbose_name='почтовый индекс')),
                ('city', models.CharField(max_length=100, verbose_name='город')),
                ('street', models.CharField(max_length=100, verbose_name='улица')),
                ('house', models.CharField(max_length=100, verbose_name='дом')),
                ('building', models.CharField(blank=True, max_length=100, verbose_name='корпус')),
                ('apartment', models.CharField(blank=True, max_length=100, verbose_name='квартира')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('paid', models.BooleanField(default=False, verbose_name='Оплачено')),
                ('buyer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Покупатель')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='products.product')),
            ],
        ),
    ]
